### PR TITLE
Add sysconfig and rhel support

### PR DESCRIPTION
**Pull request by mat1010**
Hi, thanks for the module - it works great - also with rhel based systems.

I added support to manage the `/etc/sysconfig/sogo` file for RedHat and `/etc/default/sogo` for Debian based systems. Would you mind to review and test this PR with a Debian based System? Unfortunately I don't have any Debian systems at hand. Let me know if you have doubts with that change.

Thanks in advance

### CODE REVIEW

**Comment by Thor77** [comment]
Thanks for your PR!
I would prefer the names `environment` and `environment_path` for the parameters, as that's more distro-independent.

**Comment by mat1010** [comment]
Thx for your reply. Sounds good to me. We could also go with `envconfig` and `envconfig_path` which might be a bit more intuitive.

**Comment by Thor77** [comment]
`envconfig` and `envconfig_path` are also fine for me.

**Comment by mat1010** [comment]
Great, I renamed the `sysconfig` to `envconfig`. I also introduced a check that we only tempalte the envconfig file if the envconfig hash is not empty, this shoud avoid to touch a already modified environment config file on existing installations.

I would also add, within another PR, unit tests if you are interested.

**Comment by Thor77** [comment]
Merged, thanks a lot!

> I would also add, within another PR, unit tests if you are interested.

Sure, I just didn't have the time to start writing tests for all of my puppet modules, yet...

**Comment by Thor77** [comment]
I also created a new release on puppet forge (0.2.0) :rocket:

**Comment by mat1010** [comment]
Thanks a lot - and sorry for missing the documentation part for the new parameters within the `init.pp`

**Pull request merged**
